sudo: false
language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
install:
- true
script:
- ./gradlew build
- ./gradlew crashlyticsUploadDistributionDebug
before_install:
- openssl aes-256-cbc -K $encrypted_2e7f0e2d31e5_key -iv $encrypted_2e7f0e2d31e5_iv
  -in fabric.properties.enc -out fabric.properties -d
