sudo: false
language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-21
install:
- true
- ./gradlew assemble
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- sleep 30
- adb shell input keyevent 82 &
script:
- ./gradlew build
- ./gradlew crashlyticsUploadDistributionDebug
- ./gradlew connectedDebugAndroidTest
before_install:
- openssl aes-256-cbc -K $encrypted_2e7f0e2d31e5_key -iv $encrypted_2e7f0e2d31e5_iv
  -in app/fabric.properties.enc -out app/fabric.properties -d
